### ISSUE TITLE
Path change for Google Material Design icons codepoints

### ISSUE THREAD

**Issue by Caerind** [juliettef/IconFontCppHeaders#19]
Hello (again) !

Aside from my pull request, I think I found an issue with the MaterialDesign codepoints as the path seems to have been changed.

**Comment by juliettef** [comment]
Yes it was reworked 3 months ago but the implementation has several issues (including for ex. [#1082](https://github.com/google/material-design-icons/issues/1082)) I was hoping they would fix before I spent further time on it.
I'll keep this issue open for now, however if anyone needs the MD update, do let me know and I'll see what I can do.

**Comment by memononen** [comment]
The material icon stores the names of the icons in the ligatures, so that a string "auto_awesome" will turn into the corresponding icon i.e. when rendered on a browser. And... this can be parsed out of the font file!

Super crappy C parser here: https://gist.github.com/memononen/c6f8244fbd419971b84764387e317643

Looks like a lot of icon fonts support this. There should be ttf parsing libs for python too to make that easier and more robust.

**Comment by juliettef** [comment]
That's interesting, though it may not resolve all problems as it seems some ligatures are also duplicated (see comments in [#1082](https://github.com/google/material-design-icons/issues/1082)). I'll keep it in mind though, thanks a lot for the info.

**Comment by memononen** [comment]
Correct, it does not solve that problem.
