### ISSUE TITLE
Add Font Awesome 6

### ISSUE THREAD

**Issue by PAI5REECHO** [juliettef/IconFontCppHeaders#21]
See https://fontawesome.com/docs/changelog/

**Comment by juliettef** [comment]
I'm waiting for FortAwesome to make the v6 metadata available, see https://github.com/FortAwesome/Font-Awesome/issues/18662

- I assume that the v6 metadata will only cover the free icons, as was the case for v5. 
- For the v6 pro codepoints, you'll need the pro icons.yaml. I've asked FortAwesome to open source it back in 2020 but they refused. Since I don't have the v6 pro licence, I can't generate the pro codepoints as I did for v5 pro.

Note that you can use the v6 ttf files with the v5 codepoints though you won't get the full set.
