### ISSUE TITLE
ICON_MAX_MD from IconMaterialDesgin.h can't use in imgui

### ISSUE THREAD

**Issue by ShawnWicky** [juliettef/IconFontCppHeaders#22]
I got a error when setting the icons range using ICON_MAX_MD, here is the code 
`const ImWchar md_icons_ranges[] = { ICON_MIN_MD, ICON_MAX_MD, 0};`
And I used it to attach the ttf to my custom fonts
`io.Fonts->AddFontFromFileTTF(FONT_ICON_FILE_NAME_MD, 18.0f, &config, md_icons_ranges);`
However, There is a error in the first line said that 
`Constant expression evaluates to 1114109 which cannot be narrowed to type 'ImWchar' (aka 'unsigned short')`

**Comment by dougbinks** [comment]
This appears to be due to the `goat` icon having codepoint `0x10fffd`
https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints#L867

A workaround would be that if you don't use the `goat` icon you can use a high codepoint like `0xf900` which is larger than the other icons instead of `ICON_MAX_MD`.

**Comment by ShawnWicky** [comment]
> This appears to be due to the `goat` icon having codepoint `0x10fffd` https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints#L867
> 
> A workaround would be that if you don't use the `goat` icon you can use a high codepoint like `0xf900` which is larger than the other icons instead of `ICON_MAX_MD`.

I don't need that icon, thank you!
